# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jarvisragulassistant

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://jarvisragulassistant.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_acaff203e2da47adbd4fb4dab4fcc098 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_494b903ba80f4419bf90a0749ffc0a38 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: jarvisragulassistant.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_acaff203e2da47adbd4fb4dab4fcc098 }}/jarvis1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jarvisragulassistant'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9d197b6e581e458a8398418c3a805c68 }}
        images: 'jarvisragulassistant.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_acaff203e2da47adbd4fb4dab4fcc098 }}/jarvis1:${{ github.sha }}'